"use client";
import Footer from "./_components/Footer";
import GeriaNavbar from "./_components/GeriaNavbar";
import "./globals.css";
import { Console } from "console";
//import Footer from "./_components/Footer"

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body>
      <div id="_root" className="flex flex-col h-full">
        <GeriaNavbar />
        <div className="flex-1">
          {children}
        </div>
        <Footer />
      </div>
      </body>
    </html>
  )
}
